export type ReviewShell = "public" | "focused" | "participant";

export type ReviewScreen = {
  slug: string;
  title: string;
  route: string;
  state: string;
  group: string;
  shell: ReviewShell;
  kind:
    | "landing"
    | "eligibility"
    | "assessment"
    | "assessment-result"
    | "welcome"
    | "plan-ready"
    | "home"
    | "plan"
    | "workout"
    | "jump-ropes"
    | "programs"
    | "offer"
    | "checkout"
    | "accelerator-setup"
    | "accelerator"
    | "history"
    | "progress"
    | "nutrition"
    | "notifications"
    | "account"
    | "purchases"
    | "refund"
    | "recovery";
  variant: string;
};

export const reviewScreens: ReviewScreen[] = [
  {
    slug: "free-offer",
    title: "Free 7-Day Offer",
    route: "/",
    state: "Public visitor",
    group: "Entry and setup",
    shell: "public",
    kind: "landing",
    variant: "default",
  },
  {
    slug: "welcome-setup",
    title: "Welcome",
    route: "/welcome",
    state: "New participant handoff",
    group: "Entry and setup",
    shell: "focused",
    kind: "welcome",
    variant: "setup",
  },
  {
    slug: "before-you-start",
    title: "Before You Start",
    route: "/assessment/start",
    state: "Eligible visitor",
    group: "Entry and setup",
    shell: "focused",
    kind: "eligibility",
    variant: "default",
  },
  {
    slug: "before-you-start-ineligible",
    title: "Before You Start",
    route: "/assessment/start",
    state: "Not eligible",
    group: "Entry and setup",
    shell: "focused",
    kind: "eligibility",
    variant: "ineligible",
  },
  {
    slug: "assessment-step-1",
    title: "Assessment - Step 1",
    route: "/assessment",
    state: "No answers selected",
    group: "Entry and setup",
    shell: "focused",
    kind: "assessment",
    variant: "1",
  },
  {
    slug: "assessment-step-2",
    title: "Assessment - Step 2",
    route: "/assessment",
    state: "Typical selections",
    group: "Entry and setup",
    shell: "focused",
    kind: "assessment",
    variant: "2",
  },
  {
    slug: "assessment-step-3",
    title: "Assessment - Step 3",
    route: "/assessment",
    state: "Equipment, schedule, and optional weight",
    group: "Entry and setup",
    shell: "focused",
    kind: "assessment",
    variant: "3",
  },
  {
    slug: "assessment-result",
    title: "Your Plan Is Ready",
    route: "/assessment/complete",
    state: "New plan",
    group: "Entry and setup",
    shell: "focused",
    kind: "assessment-result",
    variant: "new",
  },
  {
    slug: "assessment-replacement",
    title: "Replace Existing Plan",
    route: "/assessment/complete",
    state: "Returning participant",
    group: "Entry and setup",
    shell: "focused",
    kind: "assessment-result",
    variant: "replace",
  },
  {
    slug: "welcome-email-sent",
    title: "Check Your Email",
    route: "/welcome",
    state: "Welcome link sent",
    group: "Entry and setup",
    shell: "focused",
    kind: "welcome",
    variant: "sent",
  },
  {
    slug: "welcome-returning",
    title: "Welcome Back",
    route: "/welcome",
    state: "Existing email",
    group: "Entry and setup",
    shell: "focused",
    kind: "welcome",
    variant: "returning",
  },
  {
    slug: "home-screen-prompt",
    title: "Keep Your Plan One Tap Away",
    route: "/plan-ready",
    state: "Mobile install prompt",
    group: "Entry and setup",
    shell: "focused",
    kind: "plan-ready",
    variant: "mobile",
  },

  {
    slug: "home-seven-day",
    title: "Home",
    route: "/home",
    state: "7-Day plan active",
    group: "Home",
    shell: "participant",
    kind: "home",
    variant: "seven-day",
  },
  {
    slug: "home-accelerator",
    title: "Home",
    route: "/home",
    state: "28-Day Accelerator active",
    group: "Home",
    shell: "participant",
    kind: "home",
    variant: "accelerator",
  },
  {
    slug: "home-no-active-plan",
    title: "Home",
    route: "/home",
    state: "No active plan",
    group: "Home",
    shell: "participant",
    kind: "home",
    variant: "empty",
  },
  {
    slug: "home-loading",
    title: "Home",
    route: "/home",
    state: "Loading",
    group: "Home",
    shell: "participant",
    kind: "home",
    variant: "loading",
  },
  {
    slug: "home-unavailable",
    title: "Home",
    route: "/home",
    state: "Data unavailable",
    group: "Home",
    shell: "participant",
    kind: "home",
    variant: "error",
  },

  {
    slug: "seven-day-overview",
    title: "Your 7-Day Plan",
    route: "/your-plan",
    state: "Plan in progress",
    group: "7-Day plan",
    shell: "participant",
    kind: "plan",
    variant: "active",
  },
  {
    slug: "seven-day-complete",
    title: "Your 7-Day Plan",
    route: "/your-plan",
    state: "Plan completed",
    group: "7-Day plan",
    shell: "participant",
    kind: "plan",
    variant: "complete",
  },
  {
    slug: "workout-ready",
    title: "Day 1 - Jump Rope + Full Body",
    route: "/your-plan/day/1",
    state: "W01 - ready now",
    group: "7-Day plan",
    shell: "participant",
    kind: "workout",
    variant: "ready-w01",
  },
  {
    slug: "workout-day-2-ready",
    title: "Day 2 - Jump Rope + Upper Body",
    route: "/your-plan/day/2",
    state: "W02 - ready now",
    group: "7-Day plan",
    shell: "participant",
    kind: "workout",
    variant: "ready-w02",
  },
  {
    slug: "workout-day-3-ready",
    title: "Day 3 - Jump Rope + Lower Body",
    route: "/your-plan/day/3",
    state: "W03 - ready from Home",
    group: "7-Day plan",
    shell: "participant",
    kind: "workout",
    variant: "ready-w03",
  },
  {
    slug: "workout-day-4-ready",
    title: "Day 4 - Jump Rope + Core",
    route: "/your-plan/day/4",
    state: "W04 - ready now",
    group: "7-Day plan",
    shell: "participant",
    kind: "workout",
    variant: "ready-w04",
  },
  {
    slug: "workout-day-5-ready",
    title: "Day 5 - Jump Rope + Total Body",
    route: "/your-plan/day/5",
    state: "W05 - ready now",
    group: "7-Day plan",
    shell: "participant",
    kind: "workout",
    variant: "ready-w05",
  },
  {
    slug: "workout-day-6-ready",
    title: "Day 6 - Jump Rope + Legs",
    route: "/your-plan/day/6",
    state: "W06 - ready now",
    group: "7-Day plan",
    shell: "participant",
    kind: "workout",
    variant: "ready-w06",
  },
  {
    slug: "workout-day-7-ready",
    title: "Day 7 - Active Recovery",
    route: "/your-plan/day/7",
    state: "W07 - ready now",
    group: "7-Day plan",
    shell: "participant",
    kind: "workout",
    variant: "ready-w07",
  },
  {
    slug: "workout-blocked",
    title: "Workout Day",
    route: "/your-plan/day/3",
    state: "Prior day incomplete",
    group: "7-Day plan",
    shell: "participant",
    kind: "workout",
    variant: "blocked",
  },
  {
    slug: "workout-scheduled",
    title: "Workout Day",
    route: "/your-plan/day/4",
    state: "Available later",
    group: "7-Day plan",
    shell: "participant",
    kind: "workout",
    variant: "scheduled",
  },
  {
    slug: "workout-completed",
    title: "Workout Day",
    route: "/your-plan/day/2",
    state: "Completed",
    group: "7-Day plan",
    shell: "participant",
    kind: "workout",
    variant: "completed",
  },
  {
    slug: "recovery-day",
    title: "Recovery Day",
    route: "/your-plan/day/7",
    state: "Active recovery",
    group: "7-Day plan",
    shell: "participant",
    kind: "workout",
    variant: "recovery",
  },
  {
    slug: "jump-rope-guide",
    title: "Choose a Jump Rope",
    route: "/jump-ropes",
    state: "Participant guide",
    group: "7-Day plan",
    shell: "participant",
    kind: "jump-ropes",
    variant: "default",
  },

  {
    slug: "programs-not-started",
    title: "My Programs",
    route: "/my-programs",
    state: "Owned - not started",
    group: "Programs",
    shell: "participant",
    kind: "programs",
    variant: "not-started",
  },
  {
    slug: "programs-active",
    title: "My Programs",
    route: "/my-programs",
    state: "Active programs",
    group: "Programs",
    shell: "participant",
    kind: "programs",
    variant: "active",
  },
  {
    slug: "programs-paused",
    title: "My Programs",
    route: "/my-programs",
    state: "Paused Accelerator",
    group: "Programs",
    shell: "participant",
    kind: "programs",
    variant: "paused",
  },
  {
    slug: "programs-completed",
    title: "My Programs",
    route: "/my-programs",
    state: "Completed programs",
    group: "Programs",
    shell: "participant",
    kind: "programs",
    variant: "complete",
  },
  {
    slug: "programs-empty",
    title: "My Programs",
    route: "/my-programs",
    state: "No paid program",
    group: "Programs",
    shell: "participant",
    kind: "programs",
    variant: "empty",
  },
  {
    slug: "programs-unavailable",
    title: "My Programs",
    route: "/my-programs",
    state: "Data unavailable",
    group: "Programs",
    shell: "participant",
    kind: "programs",
    variant: "error",
  },
  {
    slug: "accelerator-offer",
    title: "28-Day Fat Loss Accelerator",
    route: "/programs/accelerator",
    state: "Eligible buyer",
    group: "Programs",
    shell: "participant",
    kind: "offer",
    variant: "default",
  },
  {
    slug: "checkout-confirmed",
    title: "You Own It",
    route: "/checkout/accelerator/success",
    state: "Purchase confirmed",
    group: "Programs",
    shell: "participant",
    kind: "checkout",
    variant: "confirmed",
  },
  {
    slug: "checkout-processing",
    title: "Finishing Your Purchase",
    route: "/checkout/accelerator/success",
    state: "Purchase still processing",
    group: "Programs",
    shell: "participant",
    kind: "checkout",
    variant: "pending",
  },
  {
    slug: "accelerator-setup",
    title: "Set Up Your Accelerator",
    route: "/my-programs/accelerator/setup",
    state: "First start",
    group: "Programs",
    shell: "participant",
    kind: "accelerator-setup",
    variant: "default",
  },
  {
    slug: "accelerator-active",
    title: "28-Day Accelerator",
    route: "/accelerator",
    state: "Workout day",
    group: "Programs",
    shell: "participant",
    kind: "accelerator",
    variant: "active",
  },
  {
    slug: "accelerator-workout-day-9",
    title: "Day 9 - Workout B - EMOM",
    route: "/accelerator",
    state: "Workout ready",
    group: "Programs",
    shell: "participant",
    kind: "accelerator",
    variant: "workout",
  },
  {
    slug: "accelerator-rest",
    title: "28-Day Accelerator",
    route: "/accelerator",
    state: "Recovery day",
    group: "Programs",
    shell: "participant",
    kind: "accelerator",
    variant: "rest",
  },
  {
    slug: "accelerator-complete",
    title: "Accelerator Complete",
    route: "/accelerator",
    state: "Program completed",
    group: "Programs",
    shell: "participant",
    kind: "accelerator",
    variant: "complete",
  },
  {
    slug: "accelerator-history",
    title: "Program History",
    route: "/my-programs/accelerator/runs",
    state: "Previous programs",
    group: "Programs",
    shell: "participant",
    kind: "history",
    variant: "default",
  },

  {
    slug: "progress-empty",
    title: "Your Progress",
    route: "/progress",
    state: "No measurements yet",
    group: "Progress",
    shell: "participant",
    kind: "progress",
    variant: "empty",
  },
  {
    slug: "progress-active",
    title: "Your Progress",
    route: "/progress",
    state: "Active program",
    group: "Progress",
    shell: "participant",
    kind: "progress",
    variant: "active",
  },
  {
    slug: "progress-history",
    title: "Your Progress",
    route: "/progress",
    state: "Measurements and completed programs",
    group: "Progress",
    shell: "participant",
    kind: "progress",
    variant: "history",
  },
  {
    slug: "progress-unavailable",
    title: "Your Progress",
    route: "/progress",
    state: "Data unavailable",
    group: "Progress",
    shell: "participant",
    kind: "progress",
    variant: "error",
  },

  {
    slug: "nutrition-locked",
    title: "Your Nutrition",
    route: "/nutrition",
    state: "Not unlocked",
    group: "Nutrition",
    shell: "participant",
    kind: "nutrition",
    variant: "locked",
  },
  {
    slug: "nutrition-setup",
    title: "Your Nutrition",
    route: "/nutrition",
    state: "Targets not set",
    group: "Nutrition",
    shell: "participant",
    kind: "nutrition",
    variant: "setup",
  },
  {
    slug: "nutrition-active",
    title: "Your Nutrition",
    route: "/nutrition",
    state: "Targets active",
    group: "Nutrition",
    shell: "participant",
    kind: "nutrition",
    variant: "active",
  },
  {
    slug: "nutrition-target-review",
    title: "Your Nutrition",
    route: "/nutrition",
    state: "Updated measurements",
    group: "Nutrition",
    shell: "participant",
    kind: "nutrition",
    variant: "review",
  },
  {
    slug: "nutrition-unavailable",
    title: "Your Nutrition",
    route: "/nutrition",
    state: "Data unavailable",
    group: "Nutrition",
    shell: "participant",
    kind: "nutrition",
    variant: "error",
  },

  {
    slug: "notifications-unread",
    title: "Notifications",
    route: "/notifications",
    state: "Unread reminders",
    group: "Account and support",
    shell: "participant",
    kind: "notifications",
    variant: "unread",
  },
  {
    slug: "notifications-empty",
    title: "Notifications",
    route: "/notifications",
    state: "Nothing new",
    group: "Account and support",
    shell: "participant",
    kind: "notifications",
    variant: "empty",
  },
  {
    slug: "account-signed-in",
    title: "My Account",
    route: "/account",
    state: "Signed in",
    group: "Account and support",
    shell: "participant",
    kind: "account",
    variant: "signed-in",
  },
  {
    slug: "account-signed-out",
    title: "Account Access",
    route: "/account",
    state: "Signed out",
    group: "Account and support",
    shell: "public",
    kind: "account",
    variant: "signed-out",
  },
  {
    slug: "purchases",
    title: "Purchases and Billing",
    route: "/account/purchases",
    state: "Purchase on file",
    group: "Account and support",
    shell: "participant",
    kind: "purchases",
    variant: "default",
  },
  {
    slug: "refund-request",
    title: "Request a Refund",
    route: "/my-programs/accelerator/refund",
    state: "Eligible purchase",
    group: "Account and support",
    shell: "participant",
    kind: "refund",
    variant: "default",
  },
  {
    slug: "recovery",
    title: "Get a Magic Access Link",
    route: "/recover",
    state: "Signed out",
    group: "Account and support",
    shell: "public",
    kind: "recovery",
    variant: "default",
  },
];

export function getReviewScreen(slug: string): ReviewScreen | undefined {
  return reviewScreens.find((screen) => screen.slug === slug);
}

export const reviewGroups = Array.from(new Set(reviewScreens.map((screen) => screen.group)));
