import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { AppNotice } from "@/components/app-state";
import { Button } from "@/components/ui/button";
import { PuWorkoutMedia } from "@/design-system/precision/components";
import { missingVideoNotice, workoutVideoSrc } from "@/lib/workout-videos";

type WorkoutCardState =
  | { type: "blocked"; previousDay: number; availableLabel: string }
  | { type: "locked" }
  | { type: "scheduled"; availableLabel: string }
  | { type: "ready" }
  | { type: "completed" };

/**
 * Photo-free branded workout media with live availability and playback state.
 * Dynamic progress and access remain application state; the visual artwork is
 * generated by the shared Precision Utility component instead of image files.
 */
export function WorkoutMediaCard({
  dayNumber,
  dayLabel,
  code,
  title,
  coverTitle = title,
  videoSrc,
  accent = "orange",
  artworkVariant = "seven-day",
  iframeTitle,
  state,
}: {
  dayNumber: number;
  dayLabel?: string;
  code: string;
  title: string;
  coverTitle?: string;
  coverSrc?: string;
  videoSrc?: string | null;
  accent?: "orange" | "aqua";
  artworkVariant?: "seven-day" | "accelerator";
  iframeTitle?: string;
  state: WorkoutCardState;
}) {
  const [playing, setPlaying] = useState(false);
  const src = videoSrc === undefined ? workoutVideoSrc(code) : videoSrc;
  const program = artworkVariant === "accelerator" ? "28-Day Accelerator" : "7-Day Comeback Plan";
  const week = Math.max(1, Math.ceil(dayNumber / 7));
  const mediaState =
    state.type === "blocked"
      ? "locked"
      : state.type === "locked"
        ? "locked"
        : state.type === "scheduled"
          ? "scheduled"
          : state.type === "completed"
            ? "completed"
            : "ready";

  return (
    <section className="mt-6" aria-label={`Day ${dayNumber} workout video`}>
      {src && playing ? (
        <div className="aspect-video overflow-hidden rounded-[var(--pu-radius-contained)] border border-[var(--pu-border-strong)] bg-[var(--pu-media-surface-top)] shadow-[var(--pu-shadow-overlay)]">
          <iframe
            src={src}
            loading="lazy"
            allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture"
            allowFullScreen
            className="h-full w-full border-0"
            title={iframeTitle ?? `${code} - ${title}`}
          />
        </div>
      ) : (
        <PuWorkoutMedia
          className={accent === "aqua" ? "gxj-workout-media--aqua" : undefined}
          program={program}
          week={week}
          workoutNumber={dayNumber}
          title={coverTitle}
          subtitle={dayLabel ?? `Day ${dayNumber}`}
          state={!src && mediaState === "ready" ? "locked" : mediaState}
          size="hero"
          actionLabel={`Start Day ${dayNumber} workout`}
          onAction={src ? () => setPlaying(true) : undefined}
        />
      )}

      {!src ? (
        <AppNotice tone="warning" className="mt-3">
          {missingVideoNotice(code)}
        </AppNotice>
      ) : state.type === "blocked" ? (
        <AppNotice tone="warning" className="mt-3">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div>
              <strong>Complete Day {state.previousDay} First</strong>
              <div className="mt-1 text-sm">Available {state.availableLabel}</div>
            </div>
            <Button asChild size="sm" variant="outline">
              <Link to="/your-plan/day/$day" params={{ day: String(state.previousDay) }}>
                Go to Day {state.previousDay}
              </Link>
            </Button>
          </div>
        </AppNotice>
      ) : state.type === "locked" ? (
        <AppNotice tone="info" className="mt-3">
          Video unlocks with this workout. You can preview the instructions below.
        </AppNotice>
      ) : state.type === "scheduled" ? (
        <AppNotice tone="info" className="mt-3">
          Available {state.availableLabel}. Your next workout is scheduled.
        </AppNotice>
      ) : state.type === "completed" ? (
        <div className="mt-3 flex justify-end">
          <Button type="button" variant="outline" onClick={() => setPlaying(true)}>
            Replay Workout
          </Button>
        </div>
      ) : null}
    </section>
  );
}
