/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReturnRouteImport } from './routes/return'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MyProgramsRouteImport } from './routes/my-programs'
import { Route as JumpRopesRouteImport } from './routes/jump-ropes'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EmailPreferencesRouteImport } from './routes/email-preferences'
import { Route as AcceleratorRouteImport } from './routes/accelerator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YourPlanIndexRouteImport } from './routes/your-plan.index'
import { Route as AssessmentIndexRouteImport } from './routes/assessment.index'
import { Route as Start7DayRouteImport } from './routes/start.7-day'
import { Route as PreviewW01RouteImport } from './routes/preview.w01'
import { Route as PreviewAcceleratorRouteImport } from './routes/preview.accelerator'
import { Route as AssessmentStartRouteImport } from './routes/assessment.start'
import { Route as AssessmentCompleteRouteImport } from './routes/assessment.complete'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as YourPlanDayDayRouteImport } from './routes/your-plan.day.$day'
import { Route as MyProgramsAcceleratorSetupRouteImport } from './routes/my-programs_.accelerator.setup'
import { Route as MyProgramsAcceleratorRunsRouteImport } from './routes/my-programs_.accelerator.runs'
import { Route as CheckoutAcceleratorSuccessRouteImport } from './routes/checkout.accelerator.success'
import { Route as ApiPublicReleaseRouteImport } from './routes/api/public/release'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe/webhook'
import { Route as ApiPublicEmailWebhookRouteImport } from './routes/api/public/email/webhook'
import { Route as ApiPublicEmailDispatchRouteImport } from './routes/api/public/email/dispatch'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnRoute = ReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProgramsRoute = MyProgramsRouteImport.update({
  id: '/my-programs',
  path: '/my-programs',
  getParentRoute: () => rootRouteImport,
} as any)
const JumpRopesRoute = JumpRopesRouteImport.update({
  id: '/jump-ropes',
  path: '/jump-ropes',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailPreferencesRoute = EmailPreferencesRouteImport.update({
  id: '/email-preferences',
  path: '/email-preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceleratorRoute = AcceleratorRouteImport.update({
  id: '/accelerator',
  path: '/accelerator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YourPlanIndexRoute = YourPlanIndexRouteImport.update({
  id: '/your-plan/',
  path: '/your-plan/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIndexRoute = AssessmentIndexRouteImport.update({
  id: '/assessment/',
  path: '/assessment/',
  getParentRoute: () => rootRouteImport,
} as any)
const Start7DayRoute = Start7DayRouteImport.update({
  id: '/start/7-day',
  path: '/start/7-day',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewW01Route = PreviewW01RouteImport.update({
  id: '/preview/w01',
  path: '/preview/w01',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewAcceleratorRoute = PreviewAcceleratorRouteImport.update({
  id: '/preview/accelerator',
  path: '/preview/accelerator',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentStartRoute = AssessmentStartRouteImport.update({
  id: '/assessment/start',
  path: '/assessment/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentCompleteRoute = AssessmentCompleteRouteImport.update({
  id: '/assessment/complete',
  path: '/assessment/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const YourPlanDayDayRoute = YourPlanDayDayRouteImport.update({
  id: '/your-plan/day/$day',
  path: '/your-plan/day/$day',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProgramsAcceleratorSetupRoute =
  MyProgramsAcceleratorSetupRouteImport.update({
    id: '/my-programs_/accelerator/setup',
    path: '/my-programs/accelerator/setup',
    getParentRoute: () => rootRouteImport,
  } as any)
const MyProgramsAcceleratorRunsRoute =
  MyProgramsAcceleratorRunsRouteImport.update({
    id: '/my-programs_/accelerator/runs',
    path: '/my-programs/accelerator/runs',
    getParentRoute: () => rootRouteImport,
  } as any)
const CheckoutAcceleratorSuccessRoute =
  CheckoutAcceleratorSuccessRouteImport.update({
    id: '/checkout/accelerator/success',
    path: '/checkout/accelerator/success',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicReleaseRoute = ApiPublicReleaseRouteImport.update({
  id: '/api/public/release',
  path: '/api/public/release',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmailWebhookRoute = ApiPublicEmailWebhookRouteImport.update({
  id: '/api/public/email/webhook',
  path: '/api/public/email/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmailDispatchRoute = ApiPublicEmailDispatchRouteImport.update({
  id: '/api/public/email/dispatch',
  path: '/api/public/email/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accelerator': typeof AcceleratorRoute
  '/email-preferences': typeof EmailPreferencesRoute
  '/home': typeof HomeRoute
  '/jump-ropes': typeof JumpRopesRoute
  '/my-programs': typeof MyProgramsRoute
  '/notifications': typeof NotificationsRoute
  '/nutrition': typeof NutritionRoute
  '/programs': typeof ProgramsRoute
  '/progress': typeof ProgressRoute
  '/recover': typeof RecoverRoute
  '/return': typeof ReturnRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/assessment/complete': typeof AssessmentCompleteRoute
  '/assessment/start': typeof AssessmentStartRoute
  '/preview/accelerator': typeof PreviewAcceleratorRoute
  '/preview/w01': typeof PreviewW01Route
  '/start/7-day': typeof Start7DayRoute
  '/assessment/': typeof AssessmentIndexRoute
  '/your-plan/': typeof YourPlanIndexRoute
  '/api/public/release': typeof ApiPublicReleaseRoute
  '/checkout/accelerator/success': typeof CheckoutAcceleratorSuccessRoute
  '/my-programs/accelerator/runs': typeof MyProgramsAcceleratorRunsRoute
  '/my-programs/accelerator/setup': typeof MyProgramsAcceleratorSetupRoute
  '/your-plan/day/$day': typeof YourPlanDayDayRoute
  '/api/public/email/dispatch': typeof ApiPublicEmailDispatchRoute
  '/api/public/email/webhook': typeof ApiPublicEmailWebhookRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accelerator': typeof AcceleratorRoute
  '/email-preferences': typeof EmailPreferencesRoute
  '/home': typeof HomeRoute
  '/jump-ropes': typeof JumpRopesRoute
  '/my-programs': typeof MyProgramsRoute
  '/notifications': typeof NotificationsRoute
  '/nutrition': typeof NutritionRoute
  '/programs': typeof ProgramsRoute
  '/progress': typeof ProgressRoute
  '/recover': typeof RecoverRoute
  '/return': typeof ReturnRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/assessment/complete': typeof AssessmentCompleteRoute
  '/assessment/start': typeof AssessmentStartRoute
  '/preview/accelerator': typeof PreviewAcceleratorRoute
  '/preview/w01': typeof PreviewW01Route
  '/start/7-day': typeof Start7DayRoute
  '/assessment': typeof AssessmentIndexRoute
  '/your-plan': typeof YourPlanIndexRoute
  '/api/public/release': typeof ApiPublicReleaseRoute
  '/checkout/accelerator/success': typeof CheckoutAcceleratorSuccessRoute
  '/my-programs/accelerator/runs': typeof MyProgramsAcceleratorRunsRoute
  '/my-programs/accelerator/setup': typeof MyProgramsAcceleratorSetupRoute
  '/your-plan/day/$day': typeof YourPlanDayDayRoute
  '/api/public/email/dispatch': typeof ApiPublicEmailDispatchRoute
  '/api/public/email/webhook': typeof ApiPublicEmailWebhookRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accelerator': typeof AcceleratorRoute
  '/email-preferences': typeof EmailPreferencesRoute
  '/home': typeof HomeRoute
  '/jump-ropes': typeof JumpRopesRoute
  '/my-programs': typeof MyProgramsRoute
  '/notifications': typeof NotificationsRoute
  '/nutrition': typeof NutritionRoute
  '/programs': typeof ProgramsRoute
  '/progress': typeof ProgressRoute
  '/recover': typeof RecoverRoute
  '/return': typeof ReturnRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/assessment/complete': typeof AssessmentCompleteRoute
  '/assessment/start': typeof AssessmentStartRoute
  '/preview/accelerator': typeof PreviewAcceleratorRoute
  '/preview/w01': typeof PreviewW01Route
  '/start/7-day': typeof Start7DayRoute
  '/assessment/': typeof AssessmentIndexRoute
  '/your-plan/': typeof YourPlanIndexRoute
  '/api/public/release': typeof ApiPublicReleaseRoute
  '/checkout/accelerator/success': typeof CheckoutAcceleratorSuccessRoute
  '/my-programs_/accelerator/runs': typeof MyProgramsAcceleratorRunsRoute
  '/my-programs_/accelerator/setup': typeof MyProgramsAcceleratorSetupRoute
  '/your-plan/day/$day': typeof YourPlanDayDayRoute
  '/api/public/email/dispatch': typeof ApiPublicEmailDispatchRoute
  '/api/public/email/webhook': typeof ApiPublicEmailWebhookRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accelerator'
    | '/email-preferences'
    | '/home'
    | '/jump-ropes'
    | '/my-programs'
    | '/notifications'
    | '/nutrition'
    | '/programs'
    | '/progress'
    | '/recover'
    | '/return'
    | '/sitemap.xml'
    | '/admin/customers'
    | '/assessment/complete'
    | '/assessment/start'
    | '/preview/accelerator'
    | '/preview/w01'
    | '/start/7-day'
    | '/assessment/'
    | '/your-plan/'
    | '/api/public/release'
    | '/checkout/accelerator/success'
    | '/my-programs/accelerator/runs'
    | '/my-programs/accelerator/setup'
    | '/your-plan/day/$day'
    | '/api/public/email/dispatch'
    | '/api/public/email/webhook'
    | '/api/public/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accelerator'
    | '/email-preferences'
    | '/home'
    | '/jump-ropes'
    | '/my-programs'
    | '/notifications'
    | '/nutrition'
    | '/programs'
    | '/progress'
    | '/recover'
    | '/return'
    | '/sitemap.xml'
    | '/admin/customers'
    | '/assessment/complete'
    | '/assessment/start'
    | '/preview/accelerator'
    | '/preview/w01'
    | '/start/7-day'
    | '/assessment'
    | '/your-plan'
    | '/api/public/release'
    | '/checkout/accelerator/success'
    | '/my-programs/accelerator/runs'
    | '/my-programs/accelerator/setup'
    | '/your-plan/day/$day'
    | '/api/public/email/dispatch'
    | '/api/public/email/webhook'
    | '/api/public/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/accelerator'
    | '/email-preferences'
    | '/home'
    | '/jump-ropes'
    | '/my-programs'
    | '/notifications'
    | '/nutrition'
    | '/programs'
    | '/progress'
    | '/recover'
    | '/return'
    | '/sitemap.xml'
    | '/admin/customers'
    | '/assessment/complete'
    | '/assessment/start'
    | '/preview/accelerator'
    | '/preview/w01'
    | '/start/7-day'
    | '/assessment/'
    | '/your-plan/'
    | '/api/public/release'
    | '/checkout/accelerator/success'
    | '/my-programs_/accelerator/runs'
    | '/my-programs_/accelerator/setup'
    | '/your-plan/day/$day'
    | '/api/public/email/dispatch'
    | '/api/public/email/webhook'
    | '/api/public/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceleratorRoute: typeof AcceleratorRoute
  EmailPreferencesRoute: typeof EmailPreferencesRoute
  HomeRoute: typeof HomeRoute
  JumpRopesRoute: typeof JumpRopesRoute
  MyProgramsRoute: typeof MyProgramsRoute
  NotificationsRoute: typeof NotificationsRoute
  NutritionRoute: typeof NutritionRoute
  ProgramsRoute: typeof ProgramsRoute
  ProgressRoute: typeof ProgressRoute
  RecoverRoute: typeof RecoverRoute
  ReturnRoute: typeof ReturnRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AssessmentCompleteRoute: typeof AssessmentCompleteRoute
  AssessmentStartRoute: typeof AssessmentStartRoute
  PreviewAcceleratorRoute: typeof PreviewAcceleratorRoute
  PreviewW01Route: typeof PreviewW01Route
  Start7DayRoute: typeof Start7DayRoute
  AssessmentIndexRoute: typeof AssessmentIndexRoute
  YourPlanIndexRoute: typeof YourPlanIndexRoute
  ApiPublicReleaseRoute: typeof ApiPublicReleaseRoute
  CheckoutAcceleratorSuccessRoute: typeof CheckoutAcceleratorSuccessRoute
  MyProgramsAcceleratorRunsRoute: typeof MyProgramsAcceleratorRunsRoute
  MyProgramsAcceleratorSetupRoute: typeof MyProgramsAcceleratorSetupRoute
  YourPlanDayDayRoute: typeof YourPlanDayDayRoute
  ApiPublicEmailDispatchRoute: typeof ApiPublicEmailDispatchRoute
  ApiPublicEmailWebhookRoute: typeof ApiPublicEmailWebhookRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return': {
      id: '/return'
      path: '/return'
      fullPath: '/return'
      preLoaderRoute: typeof ReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-programs': {
      id: '/my-programs'
      path: '/my-programs'
      fullPath: '/my-programs'
      preLoaderRoute: typeof MyProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jump-ropes': {
      id: '/jump-ropes'
      path: '/jump-ropes'
      fullPath: '/jump-ropes'
      preLoaderRoute: typeof JumpRopesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-preferences': {
      id: '/email-preferences'
      path: '/email-preferences'
      fullPath: '/email-preferences'
      preLoaderRoute: typeof EmailPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accelerator': {
      id: '/accelerator'
      path: '/accelerator'
      fullPath: '/accelerator'
      preLoaderRoute: typeof AcceleratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/your-plan/': {
      id: '/your-plan/'
      path: '/your-plan'
      fullPath: '/your-plan/'
      preLoaderRoute: typeof YourPlanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/': {
      id: '/assessment/'
      path: '/assessment'
      fullPath: '/assessment/'
      preLoaderRoute: typeof AssessmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/7-day': {
      id: '/start/7-day'
      path: '/start/7-day'
      fullPath: '/start/7-day'
      preLoaderRoute: typeof Start7DayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/w01': {
      id: '/preview/w01'
      path: '/preview/w01'
      fullPath: '/preview/w01'
      preLoaderRoute: typeof PreviewW01RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/accelerator': {
      id: '/preview/accelerator'
      path: '/preview/accelerator'
      fullPath: '/preview/accelerator'
      preLoaderRoute: typeof PreviewAcceleratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/start': {
      id: '/assessment/start'
      path: '/assessment/start'
      fullPath: '/assessment/start'
      preLoaderRoute: typeof AssessmentStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/complete': {
      id: '/assessment/complete'
      path: '/assessment/complete'
      fullPath: '/assessment/complete'
      preLoaderRoute: typeof AssessmentCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/your-plan/day/$day': {
      id: '/your-plan/day/$day'
      path: '/your-plan/day/$day'
      fullPath: '/your-plan/day/$day'
      preLoaderRoute: typeof YourPlanDayDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-programs_/accelerator/setup': {
      id: '/my-programs_/accelerator/setup'
      path: '/my-programs/accelerator/setup'
      fullPath: '/my-programs/accelerator/setup'
      preLoaderRoute: typeof MyProgramsAcceleratorSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-programs_/accelerator/runs': {
      id: '/my-programs_/accelerator/runs'
      path: '/my-programs/accelerator/runs'
      fullPath: '/my-programs/accelerator/runs'
      preLoaderRoute: typeof MyProgramsAcceleratorRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/accelerator/success': {
      id: '/checkout/accelerator/success'
      path: '/checkout/accelerator/success'
      fullPath: '/checkout/accelerator/success'
      preLoaderRoute: typeof CheckoutAcceleratorSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/release': {
      id: '/api/public/release'
      path: '/api/public/release'
      fullPath: '/api/public/release'
      preLoaderRoute: typeof ApiPublicReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email/webhook': {
      id: '/api/public/email/webhook'
      path: '/api/public/email/webhook'
      fullPath: '/api/public/email/webhook'
      preLoaderRoute: typeof ApiPublicEmailWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email/dispatch': {
      id: '/api/public/email/dispatch'
      path: '/api/public/email/dispatch'
      fullPath: '/api/public/email/dispatch'
      preLoaderRoute: typeof ApiPublicEmailDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceleratorRoute: AcceleratorRoute,
  EmailPreferencesRoute: EmailPreferencesRoute,
  HomeRoute: HomeRoute,
  JumpRopesRoute: JumpRopesRoute,
  MyProgramsRoute: MyProgramsRoute,
  NotificationsRoute: NotificationsRoute,
  NutritionRoute: NutritionRoute,
  ProgramsRoute: ProgramsRoute,
  ProgressRoute: ProgressRoute,
  RecoverRoute: RecoverRoute,
  ReturnRoute: ReturnRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AssessmentCompleteRoute: AssessmentCompleteRoute,
  AssessmentStartRoute: AssessmentStartRoute,
  PreviewAcceleratorRoute: PreviewAcceleratorRoute,
  PreviewW01Route: PreviewW01Route,
  Start7DayRoute: Start7DayRoute,
  AssessmentIndexRoute: AssessmentIndexRoute,
  YourPlanIndexRoute: YourPlanIndexRoute,
  ApiPublicReleaseRoute: ApiPublicReleaseRoute,
  CheckoutAcceleratorSuccessRoute: CheckoutAcceleratorSuccessRoute,
  MyProgramsAcceleratorRunsRoute: MyProgramsAcceleratorRunsRoute,
  MyProgramsAcceleratorSetupRoute: MyProgramsAcceleratorSetupRoute,
  YourPlanDayDayRoute: YourPlanDayDayRoute,
  ApiPublicEmailDispatchRoute: ApiPublicEmailDispatchRoute,
  ApiPublicEmailWebhookRoute: ApiPublicEmailWebhookRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
