/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as JumpRopesRouteImport } from './routes/jump-ropes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YourPlanIndexRouteImport } from './routes/your-plan.index'
import { Route as AssessmentIndexRouteImport } from './routes/assessment.index'
import { Route as PreviewW01RouteImport } from './routes/preview.w01'
import { Route as AssessmentStartRouteImport } from './routes/assessment.start'
import { Route as AssessmentCompleteRouteImport } from './routes/assessment.complete'
import { Route as YourPlanDayDayRouteImport } from './routes/your-plan.day.$day'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const JumpRopesRoute = JumpRopesRouteImport.update({
  id: '/jump-ropes',
  path: '/jump-ropes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YourPlanIndexRoute = YourPlanIndexRouteImport.update({
  id: '/your-plan/',
  path: '/your-plan/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIndexRoute = AssessmentIndexRouteImport.update({
  id: '/assessment/',
  path: '/assessment/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewW01Route = PreviewW01RouteImport.update({
  id: '/preview/w01',
  path: '/preview/w01',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentStartRoute = AssessmentStartRouteImport.update({
  id: '/assessment/start',
  path: '/assessment/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentCompleteRoute = AssessmentCompleteRouteImport.update({
  id: '/assessment/complete',
  path: '/assessment/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const YourPlanDayDayRoute = YourPlanDayDayRouteImport.update({
  id: '/your-plan/day/$day',
  path: '/your-plan/day/$day',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jump-ropes': typeof JumpRopesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/assessment/complete': typeof AssessmentCompleteRoute
  '/assessment/start': typeof AssessmentStartRoute
  '/preview/w01': typeof PreviewW01Route
  '/assessment/': typeof AssessmentIndexRoute
  '/your-plan/': typeof YourPlanIndexRoute
  '/your-plan/day/$day': typeof YourPlanDayDayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jump-ropes': typeof JumpRopesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/assessment/complete': typeof AssessmentCompleteRoute
  '/assessment/start': typeof AssessmentStartRoute
  '/preview/w01': typeof PreviewW01Route
  '/assessment': typeof AssessmentIndexRoute
  '/your-plan': typeof YourPlanIndexRoute
  '/your-plan/day/$day': typeof YourPlanDayDayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jump-ropes': typeof JumpRopesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/assessment/complete': typeof AssessmentCompleteRoute
  '/assessment/start': typeof AssessmentStartRoute
  '/preview/w01': typeof PreviewW01Route
  '/assessment/': typeof AssessmentIndexRoute
  '/your-plan/': typeof YourPlanIndexRoute
  '/your-plan/day/$day': typeof YourPlanDayDayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jump-ropes'
    | '/sitemap.xml'
    | '/assessment/complete'
    | '/assessment/start'
    | '/preview/w01'
    | '/assessment/'
    | '/your-plan/'
    | '/your-plan/day/$day'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/jump-ropes'
    | '/sitemap.xml'
    | '/assessment/complete'
    | '/assessment/start'
    | '/preview/w01'
    | '/assessment'
    | '/your-plan'
    | '/your-plan/day/$day'
  id:
    | '__root__'
    | '/'
    | '/jump-ropes'
    | '/sitemap.xml'
    | '/assessment/complete'
    | '/assessment/start'
    | '/preview/w01'
    | '/assessment/'
    | '/your-plan/'
    | '/your-plan/day/$day'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JumpRopesRoute: typeof JumpRopesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AssessmentCompleteRoute: typeof AssessmentCompleteRoute
  AssessmentStartRoute: typeof AssessmentStartRoute
  PreviewW01Route: typeof PreviewW01Route
  AssessmentIndexRoute: typeof AssessmentIndexRoute
  YourPlanIndexRoute: typeof YourPlanIndexRoute
  YourPlanDayDayRoute: typeof YourPlanDayDayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jump-ropes': {
      id: '/jump-ropes'
      path: '/jump-ropes'
      fullPath: '/jump-ropes'
      preLoaderRoute: typeof JumpRopesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/your-plan/': {
      id: '/your-plan/'
      path: '/your-plan'
      fullPath: '/your-plan/'
      preLoaderRoute: typeof YourPlanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/': {
      id: '/assessment/'
      path: '/assessment'
      fullPath: '/assessment/'
      preLoaderRoute: typeof AssessmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/w01': {
      id: '/preview/w01'
      path: '/preview/w01'
      fullPath: '/preview/w01'
      preLoaderRoute: typeof PreviewW01RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/start': {
      id: '/assessment/start'
      path: '/assessment/start'
      fullPath: '/assessment/start'
      preLoaderRoute: typeof AssessmentStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/complete': {
      id: '/assessment/complete'
      path: '/assessment/complete'
      fullPath: '/assessment/complete'
      preLoaderRoute: typeof AssessmentCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/your-plan/day/$day': {
      id: '/your-plan/day/$day'
      path: '/your-plan/day/$day'
      fullPath: '/your-plan/day/$day'
      preLoaderRoute: typeof YourPlanDayDayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JumpRopesRoute: JumpRopesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AssessmentCompleteRoute: AssessmentCompleteRoute,
  AssessmentStartRoute: AssessmentStartRoute,
  PreviewW01Route: PreviewW01Route,
  AssessmentIndexRoute: AssessmentIndexRoute,
  YourPlanIndexRoute: YourPlanIndexRoute,
  YourPlanDayDayRoute: YourPlanDayDayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
