// Generated by bun run refunds:db:types from isolated migration replay.
export type RefundRpcArgs = {
  confirm_accelerator_full_refund: {
    p_source_reference: string;
    p_charge_id: string;
    p_amount_cents: number;
    p_currency: string;
    p_refund_ids: string[];
  };
  get_accelerator_refund_purchases: { p_customer_id: string };
  get_accelerator_refund_queue: { p_reviewer_id: string };
  request_accelerator_refund: { p_customer_id: string; p_purchase_id: string };
};
