// Generated by bun run signup:db:types from an isolated migration replay.
export type SignupRecoveryRows = {
  lead_intakes: {
    intake_id: string;
    token_hash: string;
    email_normalized: string;
    email_original: string;
    first_name: string;
    consent_copy: string;
    consent_version: string;
    consent_at: string;
    source: string;
    landing_path: string | null;
    referrer_origin: string | null;
    attribution: unknown;
    marketing_consent_active: boolean;
    marketing_consent_at: string;
    bound_submission_id: string | null;
    completed_lead_plan_id: string | null;
    completed_at: string | null;
    expires_at: string;
    created_at: string;
    updated_at: string;
    controlled_test: boolean;
  };
  lead_intake_sessions: {
    token_hash: string;
    intake_id: string;
    expires_at: string;
    created_at: string;
  };
  lead_intake_welcome_jobs: {
    job_id: string;
    intake_id: string;
    idempotency_key: string;
    token_hash: string | null;
    token_expires_at: string | null;
    status: string;
    attempt_count: number;
    claim_token: string | null;
    lease_expires_at: string | null;
    next_attempt_at: string | null;
    first_provider_attempt_at: string | null;
    provider_key: string | null;
    provider_message_id: string | null;
    provider_accepted_at: string | null;
    delivery_status: string;
    last_error_code: string | null;
    created_at: string;
  };
  lead_plan_completed_runs: {
    plan_version_id: string;
    lead_plan_id: string;
    assessment_json: unknown;
    plan_json: unknown;
    completions: unknown;
    plan_start_on: string;
    plan_time_zone: string;
    archived_at: string;
  };
};
